// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8fudufdb81EmsK-XLAuzeTf57b5d9LEA',
    appId: '1:534586490308:web:af338685cded48013d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    authDomain: 'snapmugflutter.firebaseapp.com',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
    measurementId: 'G-7PBECNZRNE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhK5vHpxzCh_jgP7sfuWMabS77lS7SFVs',
    appId: '1:534586490308:android:7970ba169e83284d3d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMI9L_3oFY13wPgHY7-nhZ7TXrZDpuBVQ',
    appId: '1:534586490308:ios:ebfd47f72a4399b23d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
    androidClientId:
        '534586490308-5klhe53qknd88mf2s3earqhuh7jvonkg.apps.googleusercontent.com',
    iosClientId:
        '534586490308-iv08cni8e1c6vmnnmo1rvqcdjn2n4qhv.apps.googleusercontent.com',
    iosBundleId: 'com.worksmartgroup.snapmug',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMI9L_3oFY13wPgHY7-nhZ7TXrZDpuBVQ',
    appId: '1:534586490308:ios:94730a8adffe7d593d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
    androidClientId:
        '534586490308-5klhe53qknd88mf2s3earqhuh7jvonkg.apps.googleusercontent.com',
    iosClientId:
        '534586490308-0davam39mff5fv2dbg33r89ode77hajp.apps.googleusercontent.com',
    iosBundleId: 'com.example.userSnapMug',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8fudufdb81EmsK-XLAuzeTf57b5d9LEA',
    appId: '1:534586490308:web:6ddf1b7b82b245d13d7891',
    messagingSenderId: '534586490308',
    projectId: 'snapmugflutter',
    authDomain: 'snapmugflutter.firebaseapp.com',
    databaseURL: 'https://snapmugflutter-default-rtdb.firebaseio.com',
    storageBucket: 'snapmugflutter.appspot.com',
    measurementId: 'G-BMN44NKPNJ',
  );
}
